[[redirects]]
  from = "/profilephotoeditor"
  to = "https://profilepicture.app"
  status = 301
  force = true

[build]
  publish = "/"  # Serves files from the root directory
  functions = "netlify/functions"  # Matches your functions directory setting

[[edge_functions]]
  path = "/github-data"
  function = "github-data"
