[[redirects]]
  from = "/profilephotoeditor"
  to = "https://profilepicture.app"
  status = 301
  force = true

[build]
  command = "your-build-command"
  publish = "your-publish-directory"

[[edge_functions]]
  path = "/github-data"
  function = "github-data"
