[[redirects]]
  from = "/profilephotoeditor"
  to = "https://profilepicture.app"
  status = 301
  force = true

[[redirects]]
  from = "/github-contribution-chart-remixer"
  to = "https://commit365.dev/gitchart"
  status = 301
  force = true

[[redirects]]
  from = "/copytext"
  to = "/cannedsupport"
  status = 301
  force = true

[build]
  publish = "/"  # Serves files from the root directory
  functions = "netlify/functions"  # Matches your functions directory setting

[[edge_functions]]
  path = "/github-data"
  function = "github-data"

[[edge_functions]]
  path = "/google-sheet"
  function = "google-sheet" 
